/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programaritmatikaa;

/**
 *
 * @author -asus-
 */
public class Frame1 extends javax.swing.JFrame {

    String jns = "";
    int jml;
    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
        
        jns = null;
        panel.setVisible(false);
        
               bil3.setVisible(false);
               bil4.setVisible(false);               
               b3.setVisible(false);
               b4.setVisible(false);
               bil1.setVisible(false);
               bil2.setVisible(false);
               b1.setVisible(false);
               b2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        bil3 = new javax.swing.JTextField();
        jmlbil = new javax.swing.JComboBox<>();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        bil4 = new javax.swing.JTextField();
        b4 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Bhitung = new javax.swing.JButton();
        thasil = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel5.setText("Jenis Aritmatika");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 70, 90, 17);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih salah satu--", "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(170, 70, 150, 20);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel6.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 20, 160, 19);

        panel.setBackground(new java.awt.Color(255, 102, 102));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("OPERASI"));

        bil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil3ActionPerformed(evt);
            }
        });

        jmlbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "2", "3", "4" }));
        jmlbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlbilActionPerformed(evt);
            }
        });

        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });

        bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil2ActionPerformed(evt);
            }
        });

        bil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil4ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        b4.setText("Bilangan 4");

        b3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        b3.setText("Bilangan 3");

        b2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        b2.setText("Bilangan 2");

        b1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        b1.setText("Bilangan 1");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setText("Jumlah Bilangan");

        Bhitung.setText("HITUNG");
        Bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BhitungActionPerformed(evt);
            }
        });

        thasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thasilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jmlbil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(bil1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(bil2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(bil3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(bil4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(140, 140, 140)
                            .addComponent(Bhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addComponent(thasil, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jmlbil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bil1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bil2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b3)
                        .addComponent(bil3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(b4)
                        .addComponent(bil4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addComponent(Bhitung)
                    .addGap(7, 7, 7)
                    .addComponent(thasil, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(panel);
        panel.setBounds(20, 110, 340, 360);

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 420, 480);

        setBounds(0, 0, 431, 517);
    }// </editor-fold>//GEN-END:initComponents

    private void bil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil3ActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil1ActionPerformed

    private void bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil2ActionPerformed

    private void bil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bil4ActionPerformed

    private void BhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BhitungActionPerformed
        // TODO add your handling code here:
        Double hsl = 0.0;
        Double a1,a2,a3,a4;
        a1 = Double.parseDouble(bil1.getText().toString());
        a2 = Double.parseDouble(bil2.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1 + a2;
                thasil.setText(""+a1+" + " + a2 + " = " + hsl);
            }
            
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 + a2 + a3;
                thasil.setText(""+a1+" + " + a2  + " + " + a3 + " = " + hsl);
            }
           
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 + a2 + a3 + a4;
                thasil.setText(""+a1+" + " + a2 + " + " + a3 + " + " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1 - a2;
                thasil.setText(""+a1+" - " + a2 + " = " + hsl);
            }
            
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 - a2 - a3;
                thasil.setText(""+a1+" - " + a2  + " - " + a3 + " = " + hsl);
            }
           
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 - a2 - a3 - a4;
                thasil.setText(""+a1+" - " + a2 + " - " + a3 + " - " + a4 + " = " + hsl);
            }
        }
        else if(jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1 * a2;
                thasil.setText(""+a1+" x " + a2 + " = " + hsl);
            }
            
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 * a2 * a3;
                thasil.setText(""+a1+" x " + a2  + " x " + a3 + " = " + hsl);
            }
           
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 * a2 * a3 * a4;
                thasil.setText(""+a1+" x " + a2 + " x " + a3 + " x " + a4 + " = " + hsl);
            }
        }
          else if(jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1 / a2;
                thasil.setText(""+a1+" : " + a2 + " = " + hsl);
            }
            
            if(jml == 3){
                a3 = Double.parseDouble(bil3.getText().toString());
                hsl = a1 / a2 / a3;
                thasil.setText(""+a1+" : " + a2  + " : " + a3 + " = " + hsl);
            }
           
            if(jml == 4){
                a3 = Double.parseDouble(bil3.getText().toString());
                a4 = Double.parseDouble(bil4.getText().toString());
                hsl = a1 / a2 / a3 / a4;
                thasil.setText(""+a1+" : " + a2 + " : " + a3 + " : " + a4 + " = " + hsl);
            }
        }
    }//GEN-LAST:event_BhitungActionPerformed

    private void thasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thasilActionPerformed

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed

    private void jmlbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlbilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_jmlbilActionPerformed
       public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
          jns = "Penjumlahan";
          jLabel6.setText("Penjumlahan");
          panel.setVisible(true);
          jmlbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pengurangan")){
          jns = "Pengurangan";
          jLabel6.setText("Pengurangan");
          panel.setVisible(true);
          jmlbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Perkalian")){
          jns = "Perkalian";
          jLabel6.setText("Perkalian");
          panel.setVisible(true);
          jmlbil.setEnabled(true);
        }
        else if(jenis.getSelectedItem().equals("Pembagian")){
          jns = "Pembagian";
          jLabel6.setText("Pembagian");
          panel.setVisible(true);
          jmlbil.setEnabled(true);
        }
        else{
            jns=null;
            panel.setVisible(false);
        }
    }
       
       public void getJumlah(){
          
          if(jmlbil.getSelectedItem().equals("2")){
               bil3.setVisible(false);
               bil4.setVisible(false);               
               b3.setVisible(false);
               b4.setVisible(false);
               bil1.setVisible(true);
               bil2.setVisible(true);
               b1.setVisible(true);
               b2.setVisible(true);
               jml = 2;
           }
           else if(jmlbil.getSelectedItem().equals("3")){
               bil1.setVisible(true);
               bil2.setVisible(true);
               b1.setVisible(true);
               b2.setVisible(true);
               bil3.setVisible(true);
               bil4.setVisible(false);               
               b3.setVisible(true);
               b4.setVisible(false);
               jml = 3;
           }
           else if(jmlbil.getSelectedItem().equals("4")){
               bil1.setVisible(true);
               bil2.setVisible(true);
               b1.setVisible(true);
               b2.setVisible(true);
               bil3.setVisible(true);
               bil4.setVisible(true);               
               b3.setVisible(true);
               b4.setVisible(true);
               jml = 4;
           }
           else{
               bil3.setVisible(false);
               bil4.setVisible(false);               
               b3.setVisible(false);
               b4.setVisible(false);
               bil1.setVisible(false);
               bil2.setVisible(false);
               b1.setVisible(false);
               b2.setVisible(false);
           }
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bhitung;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JTextField bil3;
    private javax.swing.JTextField bil4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JComboBox<String> jmlbil;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField thasil;
    // End of variables declaration//GEN-END:variables
}
